name:               dat
version:            0.1.0.0
license:            NONE
author:             Vito Canadi
maintainer:         vito.canadi@gmail.com
extra-source-files: CHANGELOG.md
synopsis:           Alternative generic representation of data types

ghc-options:
  - -Wunused-imports
  - -Werror
  # - -Wall

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - DefaultSignatures
  - ScopedTypeVariables
  - TypeApplications
  - DeriveGeneric

dependencies:
  - base
  - hspec
  - QuickCheck
  - generic-random

library:
  source-dirs: src

tests:
  spec:
    build-depends:
    - base
    - dat
    - hspec
    main: Spec.hs
    source-dirs: spec
